version: "3"
services:
  mysql:
    image: mysql:latest
    container_name: mysql-forum
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - social
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq-forum
    ports: 
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "admin"
    networks:
      - social

networks:
  social: 