apiVersion: v1
kind: Service
metadata:
  name: chat-service
  labels:
    app.kubernetes.io/name: chat-service
spec:
  type: {{ .Values.chatDesc.serviceType }}
  ports:
    - port: 8084
      targetPort: 8084
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: chat-service